---
- name: "Wildfly installation and configuration"
  hosts: "all"
  become: yes
  vars:
    wildfly_user: wildfly
    wildfly_group: wildfly
    wildfly:
      workdir: /opt
      download_base_url: https://download.jboss.org/wildfly/
      version: 19.0.0.Final
    wildfly_home: "{{ wildfly.workdir }}/wildfly-{{ wildfly.version }}"
    wildfly_config_base: standalone.xml
  roles:
    - jcliff
    - wildfly_systemd
  pre_tasks:

    - name: "Ensure user {{ wildfly_user }} exists."
      group:
        name: "{{ wildfly_group }}"

    - name: "Ensure group {{ wildfly_group }} exists."
      user:
        name: "{{ wildfly_user }}"
        groups: "{{ wildfly_group }}"
        state: present

    - package:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - tar
        - java-1.8.0-openjdk

    - set_fact:
        wfly_download_url: "{{ wildfly.download_base_url }}/{{ wildfly.version }}/wildfly-{{ wildfly.version }}.zip"

    - name: "Download and unzip Wildfly zipfile from {{ wfly_download_url }}"
      unarchive:
        src: "{{ wfly_download_url }}"
        dest: "{{ wildfly.workdir }}"
        remote_src: yes
        creates: "{{ wildfly_home }}"

    - file:
        path: "{{ wildfly_home }}"
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_group }}"
        recurse: yes

  post_tasks:
    - name: "Checks that Wildfly server is running and accessible"
      get_url:
        url: http://localhost:8080/
        dest: '/dev/null'
