---
- name: "Wildfly installation and configuration"
  hosts: "all"
  become: yes
  vars:
    wildfly_workdir: /opt
    wildfly_config_base: standalone.xml
  collections:
    - middleware_automation.wildfly
    - middleware_automation.jcliff
  roles:
    - jcliff
    - wildfly_install
    - wildfly_systemd
  tasks:

    - jcliff:
        wfly_home: "{{ wildfly_home }}"
        components:
          - system_properties:
            - name: JBOSS_ID
              value: "{{ instance_name }}"

    - include_role:
        name: jboss_eap
        tasks_from: jboss_cli.yml
      vars:
        jboss_home: "{{ wildfly_home  }}"
        query: '/system-property=JBOSS_ID:read-resource()'

  post_tasks:
    - wait_for:
        port: 8080

    - name: "Checks that Wildfly server is running and accessible"
      get_url:
        url: http://localhost:8080/
        dest: '/dev/null'
