---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml
  vars:
    app_url: http://people.redhat.com/~rpelisse/simple-webapp.war
    app: /tmp/simple-webapp.war
  collections:
    - middleware_automation.jcliff
  tasks:
    - name: Include jcliff role
      include_role:
        name: jcliff

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app }}"

    - jcliff:
        wfly_home: "{{ wildfly.home }}"
        subsystems:
          - system_properties:
              - name: jcliff.enabled
                value: "enabled.plus"
          - deployments:
              - name: simple-webapp
                runtime_name: simple-webapp-v1.war
                path: /tmp/simple-webapp.war
          - datasources:
              - name: ExampleDS2
                use_java_context: "true"
                jndi_name: java:jboss/datasources/ExampleDS2
                connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
                driver_name: h2

    - include_role:
        name: wildfly_common_criteria
      vars:
        java_home: '/usr/lib/jvm/jre-1.8.0-openjdk/'
        java_version: '1.8'
        jdk_id: openjdk
        jboss_home: "{{ wildfly.home }}"
        override_changed_when_if_cc_violations: False
