---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml
  collections:
    - middleware_automation.wildfly
  roles:
    - wildfly_install
    - wildfly_systemd
  tasks:

    - include_role:
        name: ../../roles/jcliff

    - set_fact:
        path_to_app: "{{ app.dir }}{{ app.name }}.{{ app.extension }}"

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app.url }}"
        dest: "{{ path_to_app }}"

    - wait_for:
        port: 8080

    - include_role:
        name: wildfly_driver
        tasks_from: jdbc_driver.yml
      vars:
        wildfly_user: wildfly
        jdbc_driver_module_dir: "{{ wildfly_home }}//modules/org/postgresql/main"
        jdbc_driver_version: 9.2-1002-jdbc4
        jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
        jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_module_name: "org.postgresql"

    - jcliff:
        wfly_home: "{{ wildfly_home }}"
        timeout: 60000
        components:
          - system_properties:
              - name: jcliff.enabled
                value: "enabled.plus"
#          - deployments:
#              - name: "{{ app.name }}"
#                runtime_name: "{{ app.name }}-v{{ app.version }}.{{ app.extension }}"
#                path: "{{ path_to_app }}"
#          - drivers:
#              - driver_name: postgresql
#                driver_module_name: org.postgresql
#                driver_class_name: org.postgresql.Driver
#                driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
#          - datasources:
#              - name: ExampleDS2
#                use_java_context: "true"
#                jndi_name: java:jboss/datasources/ExampleDS2
#                connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
#                driver_name: h2
#          - messaging_activemq:
#              jms_queue:
#                - name: myQueue
#                  entries:
#                    [
#                      "queue/myQueue",
#                      "jms/queue/myQueue",
#                      "java:jboss/exported/jms/queue/myQueue",
#                    ]
#              jms_topic:
#                - name: myTopic
#                  entries: ["MyTopic"]
